spring:
  thymeleaf:
    cache: false

---
spring:
  config:
    activate:
      on-profile:: psql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/urlshort
    username: urlshort
    password: urlshort
    tomcat:      #https://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes
      initialSize: 2
      maxActive: 10
      maxIdle: 5
      minIdle: 1
      testOnBorrow: true
      validationQuery: "SELECT 1"
      validationInterval: 30000
      removeAbandoned: true
      removeAbandonedTimeout: 180

---
spring:
  config:
    activate:
      on-profile:: hsql
  datasource:
    url: jdbc:hsqldb:file:interview
    username: SA
    password: 
